name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@0.1.3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
